# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

jobs:
- job: 'Linux'
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'
  - script: |
      pip install numpy cython pytest
      pip install -e .
      pytest
    displayName: 'Ubuntu Tests'

- job: 'Win'
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'
  - script: |
      pip install numpy cython pytest
      pip install -e .
      pytest
    displayName: 'Win Tests'

- job: 'OSX'
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'
  - script: |
      pip install numpy cython pytest
      pip install -e .
      pytest
    displayName: 'OSX Tests'
